config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  resources :products
  resources :charges, only: [:new, :create]

  root 'products#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  belongs_to :user
  belongs_to :product

  after_create :send_email
  
  def self.process_payment(user, token, product)
    amount = product.price * 100
    platform_fee = (amount.to_f / 10).to_i
    response = {}
    begin
      charge = Stripe::Charge.create({
        amount: amount.to_i,
        currency: "usd",
        source: token,
        description: "RTC charge: #{product.name}",
        application_fee: platform_fee,
        destination: product.user.uid
      })
      response[:status] = 200
      Charge.create(user: user, product: product, response: charge)
    rescue Stripe::CardError, Stripe::InvalidRequestError => e
      error = e.json_body[:error][:message]
      response[:status] = 500
      response[:error] = "Sorry! #{error}"
    end
    response
  end

  def send_email
    ChargesMailer
      .successful_charge(self)
      .deliver
  end

end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable


  has_many :products
  has_many :charges

  def self.omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = SecureRandom.hex
      user.access_code = auth.credentials.token
      user.publishable_key = auth.info.stripe_publishable_key
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_product, only: [:new, :create]

  def index
    @charges = current_user&.charges || []
  end

  def new

  end

  def create
    if @product && current_user && @product.user_id != current_user.id
      charge = Charge.process_payment(
        current_user,
        params[:stripeToken],
        @product
      )
      notice =
        if charge[:status] == 200
          'Payment was successfully processed.'
        else
          charge[:error]
        end
      redirect_to products_url, notice: notice
    else
      redirect_to products_url
    end
  end

private
  
  def set_product
    @product = Product.find(params[:product_id])
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController

  def stripe_connect
    omniauth_info = request.env["omniauth.auth"]
    @user = User.omniauth(omniauth_info)
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Stripe") if is_navigational_format?
    else
      session["devise.stripe_connect_data"] = omniauth_info
      redirect_to new_user_registration_url
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :check_role, only: [:edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show

  end

  def new
    @product = Product.new
  end

  def edit

  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private

  def set_product
    @product = Product.find(params[:id])
  end

  def check_role
    unless current_user && @product.user_id == current_user.id
      redirect_to products_url
    end
  end

  def product_params
    params.require(:product).permit(:name,
                                    :description,
                                    :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/charges/new.html.haml
= form_tag charges_path do
  %article
    - if flash[:error].present?
      #error_explanation
        %p= flash[:error]

    = form_tag charges_path do
      %article
        %label.amount
          %span
            Name: #{@product.name}
      %article
        %label.amount
          %span
            Amount: $#{@product.price}
      %article
        %label.amount
          %span
            Description: #{@product.description}
      %script.stripe-button{"data-amount" => @product.price * 100, "data-description" => @product.name, "data-key" => Rails.application.config.stripe_publishable_key, :src => "https://checkout.stripe.com/checkout.js", "data-locale" => "auto", "data-email" => "#{current_user&.email}"}
      = hidden_field_tag :product_id, @product.id

  %script{:src => "https://js.stripe.com/v3/"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Rtc
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .header.clearfix
        - if current_user
          = "Hi, #{current_user.email}"
          %br
          = link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-link'
        - else
          = link_to 'Login with Stripe', user_stripe_connect_omniauth_authorize_path

      = yield

app/views/products/_form.html.haml
= form_for product, html: { class: "form form-horizontal" } do |f|
  - if product.errors.any?
    #error_explanation
      %h2
        = pluralize(product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - product.errors.full_messages.each do |message|
          %li= message
  .form-group
    = f.label :name, class: 'control-label col-md-3'
    .col-md-9
      = f.text_field :name, class: 'form-control', required: true
  .form-group
    = f.label "Price ($)", class: 'control-label col-md-3'
    .col-md-9
      = f.text_field :price, class: 'form-control', required: true, placeholder: '12.34'
  .form-group
    = f.label :description, class: 'control-label col-md-3'
    .col-md-9
      = f.text_area :description, class: 'form-control', required: true
  .actions
    = f.submit nil, class: 'btn btn-primary'

app/views/products/edit.html.haml
%h1 Editing Product
= render 'form', product: @product

= link_to 'Back', products_path, class: 'btn btn-default'

app/views/products/index.html.haml
%p#notice= notice
%h1 Store
.row
  - @products.each do |product|
    .product.col-md-3
      %h3= link_to product.name, product
      %h4= "$ #{product.price}"
      - if current_user && product.user_id != current_user.id
        %h4= link_to 'Buy', new_charge_path(product_id: product.id), class: 'btn btn-success'
      - if current_user && product.user_id == current_user.id
        = link_to 'Edit', edit_product_path(product), class: 'btn btn-sm btn-primary'
        = link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger'
%br/
%hr
- if current_user
  = link_to 'New Product', new_product_path, class: 'btn btn-primary'

app/views/products/new.html.haml
%h1 New Product
%br
= render 'form', product: @product
= link_to 'Back', products_path, class: 'btn'

app/views/products/show.html.haml
%p#notice= notice

%p
  %b
    Name:
  %br
  = @product.name
%p
  %b
    Price:
  %br
  = @product.price
%p
  %b
    Desc:
  %br
  = @product.description

- if current_user && @product.user_id == current_user.id
  = link_to 'Edit', edit_product_path(@product), class: 'btn btn-primary'
  = link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-small btn-danger'
= link_to 'Back', products_path, class: 'btn btn-default'